Mcp3208: MCP3208 Class Reference
MCP3208 Class Reference
#include <Mcp3208.h>
Data Structures
union SpiData
Public Types
enum Channel {
SINGLE_0 = 0b1000, SINGLE_1 = 0b1001, SINGLE_2 = 0b1010, SINGLE_3 = 0b1011,
SINGLE_4 = 0b1100, SINGLE_5 = 0b1101, SINGLE_6 = 0b1110, SINGLE_7 = 0b1111,
DIFF_0PN = 0b0000, DIFF_0NP = 0b0001, DIFF_1PN = 0b0010, DIFF_1NP = 0b0011,
DIFF_2PN = 0b0100, DIFF_2NP = 0b0101, DIFF_3PN = 0b0110, DIFF_3NP = 0b0111
}
Public Member Functions
MCP3208 (uint16_t vref, uint8_t csPin, SPIClass *spi)
MCP3208 (uint16_t vref, uint8_t csPin)
void calibrate (Channel ch)
uint16_t read (Channel ch) const
template<typename T , size_t N>
void read (Channel ch, T(&data)[N]) const
template<typename T , size_t N>
void read (Channel ch, T(&data)[N], uint32_t splFreq)
template<typename T , size_t N, typename Predicate >
void read_if (Channel ch, T(&data)[N], Predicate p) const
template<typename T , size_t N, typename Predicate >
void read_if (Channel ch, T(&data)[N], uint32_t splFreq, Predicate p)
template<typename T >
void readn (Channel ch, T *data, uint16_t num) const
template<typename T >
void readn (Channel ch, T *data, uint16_t num, uint32_t splFreq)
template<typename T , typename Predicate >
void readn_if (Channel ch, T *data, uint16_t num, Predicate p) const
template<typename T , typename Predicate >
void readn_if (Channel ch, T *data, uint16_t num, uint32_t splFreq, Predicate p)
uint32_t testSplSpeed (Channel ch) const
uint32_t testSplSpeed (Channel ch, uint16_t num) const
uint32_t testSplSpeed (Channel ch, uint16_t num, uint32_t splFreq)
uint16_t toAnalog (uint16_t raw) const
uint16_t toDigital (uint16_t val) const
uint16_t getVref () const
uint16_t getAnalogRes () const
Static Public Attributes
static const uint8_t kResBits = 12
static const uint16_t kRes = (1 << kResBits)
Private Member Functions
uint16_t getSplDelay (Channel ch, uint32_t splFreq)
uint16_t transfer (SpiData cmd) const
template<typename T >
void transfer (SpiData cmd, T *data, uint16_t num) const
template<typename T >
void transfer (SpiData cmd, T *data, uint16_t num, uint16_t delay) const
Static Private Member Functions
static SpiData createCmd (Channel ch)
Private Attributes
uint16_t mVref
uint8_t mCsPin
uint32_t mSplSpeed
SPIClass * mSpi
Detailed Description
Definition at line 17 of file Mcp3208.h.
Member Enumeration Documentation
enum MCP3208::Channel
The ADC has 8 inputs, usable as 8 individually single inputs with reference to analog ground or 4 differential inputs. The polarity of each differential input can be configured.
bits 4 3 2 1
- type ch ch ch
- description
type 1 bit for single(1) or differential(0) input
ch 3 bit for channel number selection
Enumerator
SINGLE_0
single channel 0
SINGLE_1
single channel 1
SINGLE_2
single channel 2
SINGLE_3
single channel 3
SINGLE_4
single channel 4
SINGLE_5
single channel 5
SINGLE_6
single channel 6
SINGLE_7
single channel 7
DIFF_0PN
differential channel 0 (input 0+,1-)
DIFF_0NP
differential channel 0 (input 0-,1+)
DIFF_1PN
differential channel 1 (input 2+,3-)
DIFF_1NP
differential channel 1 (input 2-,3+)
DIFF_2PN
differential channel 2 (input 4+,5-)
DIFF_2NP
differential channel 2 (input 5-,5+)
DIFF_3PN
differential channel 3 (input 6+,7-)
DIFF_3NP
differential channel 3 (input 6-,7+)
Definition at line 40 of file Mcp3208.h.
Constructor & Destructor Documentation
MCP3208::MCP3208 (uint16_t vref, uint8_t csPin, SPIClass * spi)
Initiates a MCP3208 object. The chip select pin must be already configured as output.
Parameters
[in] vref ADC reference voltage in mV.
[in] csPin pin number to use for chip select.
[in] spi reference to the SPI interface to use.
Definition at line 11 of file Mcp3208.cpp.
MCP3208::MCP3208 (uint16_t vref, uint8_t csPin)
Initiates a MCP3208 object. The chip select pin must be already configured as output. The default SPI interface will be used for communication.
Parameters
[in] vref the ADC reference voltage in mV.
[in] csPin the pin number to use for chip select.
Definition at line 17 of file Mcp3208.cpp.
Member Function Documentation
void MCP3208::calibrate (Channel ch)
Calibrates read timing using the supplied channel. A calibration should be performed after evey SPI frequency changes or other events that could have an impact on the sampling speed. The SPI interface must be initialized and put in a usable state before calling this function.
Definition at line 20 of file Mcp3208.cpp.
References mSplSpeed, and testSplSpeed().
Referenced by getSplDelay().
MCP3208::SpiData MCP3208::createCmd (Channel ch) static private
Creates command data from the supplied channel.
Parameters
[in] ch the channel to create the command for.
Returns
the SPI data.
Definition at line 88 of file Mcp3208.cpp.
References MCP3208::SpiData::value.
Referenced by read(), readn(), and readn_if().
uint16_t MCP3208::getAnalogRes () const
Returns the analog resolution in µV based on the defined reference voltage.
Returns
the analog resolution in µV.
Definition at line 83 of file Mcp3208.cpp.
References kRes, and mVref.
uint16_t MCP3208::getSplDelay (Channel ch, uint32_t splFreq) private
Returns the required delay for the requested sample rate.
Parameters
[in] ch the channel to create the command for.
Returns
the delay in us.
Definition at line 99 of file Mcp3208.cpp.
References calibrate(), div_round, and mSplSpeed.
Referenced by readn(), readn_if(), and testSplSpeed().
uint16_t MCP3208::getVref () const
Returns the reference voltage.
Returns
the configured reference voltage in mV.
Definition at line 78 of file Mcp3208.cpp.
References mVref.
uint16_t MCP3208::read (Channel ch) const
Reads the supplied channel. The SPI interface must be initialized and put in a usable state before calling this function.
Parameters
[in] ch defines the channel to read from.
Returns
the converted raw value.
Definition at line 25 of file Mcp3208.cpp.
References createCmd(), and transfer().
Referenced by testSplSpeed().
template<typename T , size_t N> void MCP3208::read (Channel ch, T(&) data[N]) const inline
Reads the supplied channel and stores the data in the supplied data array. The SPI interface must be initialized and put in a usable state before calling this function.
Parameters
[in] ch defines the channel to read from.
[out] data array to store the values.
Definition at line 102 of file Mcp3208.h.
References readn().
template<typename T , size_t N> void MCP3208::read (Channel ch, T(&) data[N], uint32_t splFreq) inline
Reads the supplied channel limited to the specified frequency and stores the data in the supplied data array. The sample rate limit is software controlled, and has a low precision. The SPI interface must be initialized and put in a usable state before calling this function.
Parameters
[in] ch defines the channel to read from.
[out] data array to store the values.
[in] splFreq sample frequency limit in hz.
Definition at line 118 of file Mcp3208.h.
References readn().
template<typename T , size_t N, typename Predicate > void MCP3208::read_if (Channel ch, T(&) data[N], Predicate p) const inline
Reads the supplied channel and stores the data in the supplied data array after the predicate is true. The SPI interface must be initialized and put in a usable state before calling this function.
Parameters
[in] ch defines the channel to read from.
[out] data array to store the values.
[in] p predicate funtion to control sampling start.
Definition at line 132 of file Mcp3208.h.
References readn_if().
template<typename T , size_t N, typename Predicate > void MCP3208::read_if (Channel ch, T(&) data[N], uint32_t splFreq, Predicate p) inline
Reads the supplied channel limited to the specified frequency and stores the data in the supplied data array after the predicate is true. The sample rate limit is software controlled, and has a low precision. The SPI interface must be initialized and put in a usable state before calling this function.
Parameters
[in] ch defines the channel to read from.
[out] data array to store the values.
[in] splFreq sample frequency limit in hz.
[in] p predicate funtion to control sampling start.
Definition at line 149 of file Mcp3208.h.
References readn_if().
template<typename T > void MCP3208::readn (Channel ch, T * data, uint16_t num) const inline
Reads the supplied channel and stores N values in the supplied data array. The SPI interface must be initialized and put in a usable state before calling this function.
Parameters
[in] ch defines the channel to read from.
[out] data array to store the values.
[in] num number of reads. The data array needs to be at least that size.
Definition at line 164 of file Mcp3208.h.
References createCmd(), and transfer().
Referenced by read().
template<typename T > void MCP3208::readn (Channel ch, T * data, uint16_t num, uint32_t splFreq) inline
Reads the supplied channel limited to the specified frequency and stores N values in the supplied data array. The sample rate limit is software controlled, and has a low precision. The SPI interface must be initialized and put in a usable state before calling this function.
Parameters
[in] ch defines the channel to read from.
[out] data array to store the values.
[in] num number of reads. The data array needs to be at least that size.
[in] splFreq sample frequency limit in hz.
Definition at line 182 of file Mcp3208.h.
References createCmd(), getSplDelay(), and transfer().
template<typename T , typename Predicate > void MCP3208::readn_if (Channel ch, T * data, uint16_t num, Predicate p) const inline
Reads the supplied channel and stores N values in the supplied data array after the predicate is true. As long as the predicate is false, the function keeps sampling without storing any data. The SPI interface must be initialized and put in a usable state before calling this function.
Parameters
[in] ch defines the channel to read from.
[out] data array to store the values.
[in] num number of reads. The data array needs to be at least that size.
[in] p predicate funtion to control sampling start.
Definition at line 200 of file Mcp3208.h.
References createCmd(), and transfer().
Referenced by read_if().
template<typename T , typename Predicate > void MCP3208::readn_if (Channel ch, T * data, uint16_t num, uint32_t splFreq, Predicate p) inline
Reads the supplied channel limited to the specified frequency and stores N values in the supplied data array after the predicate is true. As long as the predicate is false, the function keeps sampling without storing any data. The SPI interface must be initialized and put in a usable state before calling this function.
Parameters
[in] ch defines the channel to read from.
[out] data array to store the values.
[in] num number of reads. The data array needs to be at least that size.
[in] splFreq sample frequency limit in hz.
[in] p predicate funtion to control sampling start.
Definition at line 222 of file Mcp3208.h.
References createCmd(), getSplDelay(), and transfer().
uint32_t MCP3208::testSplSpeed (Channel ch) const
Performs a sampling speed test over 64 reads. The SPI interface must be initialized and put in a usable state before calling this function.
Parameters
[in] ch the channel to use for the speed test.
Returns
the average sampling time needed for one sample in ns.
Definition at line 31 of file Mcp3208.cpp.
Referenced by calibrate().
uint32_t MCP3208::testSplSpeed (Channel ch, uint16_t num) const
Performs a sampling speed test. The SPI interface must be initialized and put in a usable state before calling this function.
Parameters
[in] ch the channel to use for the speed test.
[in] num the number of reads to perform.
Returns
the average sampling time needed for one sample in ns.
Definition at line 36 of file Mcp3208.cpp.
References div_round, and read().
uint32_t MCP3208::testSplSpeed (Channel ch, uint16_t num, uint32_t splFreq)
Performs a sampling speed test limited to the specified frequency. The SPI interface must be initialized and put in a usable state before calling this function.
Parameters
[in] ch the channel to use for the speed test.
[in] num the number of reads to perform.
[in] splFreq sample frequency limit in hz.
Returns
the average sampling time needed for one sample in ns.
Definition at line 49 of file Mcp3208.cpp.
References div_round, getSplDelay(), and read().
uint16_t MCP3208::toAnalog (uint16_t raw) const
Converts the supplied raw value to an analog value in mV based on the defined reference voltage.
Parameters
[in] raw the sampled ADC value.
Returns
the converted analog value in mV.
Definition at line 68 of file Mcp3208.cpp.
References kRes, and mVref.
uint16_t MCP3208::toDigital (uint16_t val) const
Converts the supplied analog value to the digital representation based on the defined reference voltage.
Parameters
[in] val the analog value in mV.
Returns
the digital representation off the supplied analog value.
Definition at line 73 of file Mcp3208.cpp.
References kRes, and mVref.
uint16_t MCP3208::transfer (SpiData cmd) const private
Transfers the supplied SPI data command.
Parameters
[in] cmd the SPI data command to transfer.
Returns
the ADC value from the SPI response.
Definition at line 112 of file Mcp3208.cpp.
References MCP3208::SpiData::hiByte, MCP3208::SpiData::loByte, mCsPin, mSpi, and MCP3208::SpiData::value.
Referenced by read(), readn(), readn_if(), and transfer().
template<typename T > void MCP3208::transfer (SpiData cmd, T * data, uint16_t num) const private
Transfers the supplied SPI data command for the requested number of samples.
Parameters
[in] cmd the SPI data command to transfer.
[out] data array to store the values.
[in] num number of reads. The data array needs to be at least that size.
Definition at line 133 of file Mcp3208.cpp.
References transfer().
template<typename T > void MCP3208::transfer (SpiData cmd, T * data, uint16_t num, uint16_t delay) const private
Transfers the supplied SPI data command for the requested number of samples with delay between reads.
Parameters
[in] cmd the SPI data command to transfer.
[out] data array to store the values.
[in] num number of reads. The data array needs to be at least that size.
[in] delay in us.
Definition at line 140 of file Mcp3208.cpp.
References transfer().
Field Documentation
const uint16_t MCP3208::kRes = (1 << kResBits) static
ADC resolution.
Definition at line 24 of file Mcp3208.h.
Referenced by getAnalogRes(), toAnalog(), and toDigital().
const uint8_t MCP3208::kResBits = 12 static
ADC resolution in bits.
Definition at line 22 of file Mcp3208.h.
uint8_t MCP3208::mCsPin private
Definition at line 349 of file Mcp3208.h.
Referenced by transfer().
SPIClass* MCP3208::mSpi private
Definition at line 351 of file Mcp3208.h.
Referenced by transfer().
uint32_t MCP3208::mSplSpeed private
Definition at line 350 of file Mcp3208.h.
Referenced by calibrate(), and getSplDelay().
uint16_t MCP3208::mVref private
Definition at line 348 of file Mcp3208.h.
Referenced by getAnalogRes(), getVref(), toAnalog(), and toDigital().
The documentation for this class was generated from the following files:
src/Mcp3208.h
src/Mcp3208.cpp